sonar.projectKey=MGTheTrain_cpp-opengl-renderer
sonar.organization=mgtt
sonar.host.url=https://sonarcloud.io

sonar.projectName=cpp-opengl-renderer
sonar.projectVersion=0.4.0

sonar.sources=modules,apps
sonar.exclusions=**/third-party/**,**/build/**,**/vcpkg_installed/**

sonar.cpd.exclusions=**/test/**

sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=.cpp,.h

sonar.cfamily.compile-commands=build/compile_commands.json
sonar.cfamily.threads=4
