FROM nginx:latest

EXPOSE 80

# Once in the dev container copy folders with .html, .js and .wasm files:
# - /workspaces/cpp-opengl-renderer/apps/rotating-textured-cube/web /usr/share/nginx/html
# - /workspaces/cpp-opengl-renderer/apps/opengl-viewer/web /usr/share/nginx/html