function(split_version_string version_string)
    string(REGEX MATCH "([0-9]+)\\.([0-9]+)\\.([0-9]+)" version_components ${version_string})
    set(CMAKE_PROJECT_VERSION_MAJOR ${CMAKE_MATCH_1} PARENT_SCOPE)
    set(CMAKE_PROJECT_VERSION_MINOR ${CMAKE_MATCH_2} PARENT_SCOPE)
    set(CMAKE_PROJECT_VERSION_PATCH ${CMAKE_MATCH_3} PARENT_SCOPE)
endfunction()
