name: Build Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yml
    with:
      run_tests: true
      upload_packages: true
      revision_number: ''
