name: CI/CT workflow for Rust libraries packaged via cargo

on:
  push:
    branches:
      - master

jobs:
  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install third-party apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        build-essential cmake \
        libxmu-dev libxi-dev libgl-dev \
        libxinerama-dev libxcursor-dev xorg-dev \
        libglu1-mesa-dev pkg-config
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
      working-directory: /tmp/   
    - name: Build and Test on Linux
      run: |
        ./compile_source_code.sh -CMakeToolchainFile /tmp/vcpkg/scripts/buildsystems/vcpkg.cmake
      working-directory: ./devops/scripts/bash/
  create-git-tags-from-version-file-job:
    runs-on: ubuntu-latest
    needs: [build_and_test_ubuntu]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create git tag from version file
        uses: MGTheTrain/github-actions/.github/actions/create-git-tag-from-version-file@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}