name: Release

on:
  push:
    branches:
      - master

jobs:
  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install third-party apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        build-essential cmake \
        libxmu-dev libxi-dev libgl-dev \
        libxinerama-dev libxcursor-dev xorg-dev \
        libglu1-mesa-dev pkg-config autoconf automake libtool
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
      working-directory: /tmp/   
    - name: Install dependencies for test executables requiring a graphical environment in this ci workflow
      run: sudo apt-get install -y xvfb
    - name: Build and Test on Linux
      run: |
        # Start Xvfb
        Xvfb :99 &
        export DISPLAY=:99
        ./compile_source_code.sh -CMakeToolchainFile /tmp/vcpkg/scripts/buildsystems/vcpkg.cmake -RunTests
      working-directory: ./devops/scripts/bash/
  create-git-tag-from-version-file:
    runs-on: ubuntu-latest
    needs: [build-and-test-ubuntu]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create git tag from version file
        uses: MGTheTrain/public-github-actions/.github/actions/create-git-tag-from-version-file@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}